# Generated by Django 5.0.6 on 2024-07-15 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('createdAt', models.DateField()),
                ('paymentDue', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('paymentTerms', models.IntegerField()),
                ('clientName', models.CharField(max_length=100)),
                ('clientEmail', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField(default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('clientAddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_address', to='api.address')),
                ('senderAddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender_address', to='api.address')),
            ],
        ),
    ]
