# Generated by Django 5.0.6 on 2024-07-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='post_code',
            new_name='postCode',
        ),
    ]
